name: Update Market Data

on:
  # Run every 15 minutes during market hours (9:15 AM to 3:30 PM IST, Mon-Fri)
  schedule:
    - cron: '*/15 3-10 * * 1-5'  # UTC time (3:45 AM to 10:00 AM UTC = 9:15 AM to 3:30 PM IST)
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main branch (for testing)
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch market data
        run: |
          python fetch_market_data.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add market_data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update market data - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
